{% set name = "caproto" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1be5815b7d4bb4b2c620e7d0e9f0c5072fb470e0d45c9d21ec8d9693ba33f6c8

build:
  noarch: python
  entry_points:
    - caproto-get = caproto.commandline.get:main
    - caproto-put = caproto.commandline.put:main
    - caproto-monitor = caproto.commandline.monitor:main
    - caproto-repeater = caproto.commandline.repeater:main
    - caproto-defaultdict-server = caproto.ioc_examples.pathological.defaultdict_server:main
    - caproto-spoof-beamline = caproto.ioc_examples.pathological.spoof_beamline:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - netifaces
    - numpy
    - trio >=0.12.1
    - curio >=1.2
    - dpkt

test:
  imports:
    - caproto

about:
  home: http://github.com/caproto/caproto
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: a bring-your-own-IO implementation of the EPICS Channel Access protocol in pure Python

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - danielballan
    - klauer
    - tacaswell
