# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 13 is conviniet
# when copying and pasting from another recipe, but not really needed.
{% set name = "caproto" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nsls-ii/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e7d01b0d413e82d696bccf8f6a36e534a6e08bb00e91e76e06b8ad67f310032e

build:
  noarch: python
  entry_points:
    - caproto-get = caproto.commandline.get:main
    - caproto-put = caproto.commandline.put:main
    - caproto-monitor = caproto.commandline.monitor:main
    - caproto-repeater = caproto.commandline.repeater:main
    - caproto-defaultdict-server = caproto.ioc_examples.defaultdict_server:main
    - caproto-spoof-beamline = caproto.ioc_examples.spoof_beamline:main
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - netifaces
    - numpy
    - trio
    - curio
    - asks

test:
  imports:
    - caproto

about:
  home: http://github.com/nsls-ii/caproto
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'a bring-your-own-IO implementation of the EPICS Channel Access protocol in pure Python'

extra:
  recipe-maintainers:
    - conda-forge/event-model
