{% set name = "caproto" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 82a70744804f2adcdbd0e40e69c910f88a84c3917dacb9a217a1425c4ebe7de2

build:
  noarch: python
  entry_points:
    - caproto-get = caproto.commandline.get:main
    - caproto-put = caproto.commandline.put:main
    - caproto-monitor = caproto.commandline.monitor:main
    - caproto-repeater = caproto.commandline.repeater:main
    - caproto-defaultdict-server = caproto.ioc_examples.pathological.defaultdict_server:main
    - caproto-spoof-beamline = caproto.ioc_examples.pathological.spoof_beamline:main
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - netifaces
    - numpy
    - trio >=0.18.0
    - curio >=1.2
    - dpkt

test:
  requires:
    - python {{ python_min }}
  imports:
    - caproto

about:
  home: http://github.com/caproto/caproto
  license: BSD-3-Clause
  license_family: BSD
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: a bring-your-own-IO implementation of the EPICS Channel Access protocol in pure Python

extra:
  recipe-maintainers:
    - conda-forge/event-model
    - danielballan
    - klauer
    - tacaswell
