travis:
  secure:
    BINSTAR_TOKEN: JC9gw2Nwoh1uVm6CsoCYKfa5T/fimiRkc84mN3O1CIjmya4JA2UoNd4prFNSPe4PTgpheI8qsv5oqudrBpRwM5qvStdCrUO+VWfgi1p7k/pjIxyPGDL/V11wvOXhtvYydmpP/kYaMK4PyhKLaIPirk4U1jjM1/PthjkuUd4TEkg3eLd8ed10C3cVSmHWgHk5mjdXfk/i/fZOJwpgIsqVOkwRvgUyZmnagOVYA5D5K6MdDJdafHicm1wj3HBE3YP2ZBuUMZHTkTuJa3/KznjQQTuCC20y54f6EHUaxAyD8XR7nhUoGR81KsmbBK34HEIBAkwIzuYUyer7VmN4y/bL7c40igqwQx+J7Sj4oOyP0+yOJ4fJY/6EGkZiRvDE/L4jUxFS9JTfOE3NelN6zhSW02kkmX8UgSfSAv6ZZfgwGEnKI1OANoy+4ekMw42/7Aln24S66SlHUZYnZPlL0I60ho8NvoqQ1Io0LIzG+YzrZGiSfqGLi2pABU0XpPcVphtfEcETUaFcL6fddY/nKE2ZNYxKfpQFUN30BODgpeG9t8xXwDN+iYLQ0+zGAOlNATkJlOKQsCaR/RE6tTLwphobKMNEEbfTxzk7irhpQWKmYzzOJ8b4PrRFFA1rQllQnW69uzjqWevdRUpjKogVLq6UgqXdIEB+9cuwQFXvAyKbgtA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
